---

- src: ANXS.apt
- src: ANXS.build-essential
- src: dwcramer.upstart
- src: nickhammond.logrotate
- src: oefenweb.postfix
- src: newrelic.newrelic-infra
  version: 0.6.1
- src: jnv.unattended-upgrades
  version: master
- src: jobscore.beats
- src: https://github.com/GSA/ansible-os-ubuntu-14
  name: gsa.ansible-os-ubuntu-14
  version: master
- src: https://github.com/GSA/ansible-os-ubuntu-16
  name: gsa.ansible-os-ubuntu-16
  version: master
