---
- name: Hardening for Ubuntu Trusty
  import_role:
    name: gsa.ansible-os-ubuntu-14
  when: ansible_distribution_release == "trusty"

- name: Hardening for Ubuntu Xenial or Bionic
  import_role:
    name: gsa.ansible-os-ubuntu-16
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"

# https://github.com/GSA/datagov-deploy/issues/2655
# Disable IPv6 without disabling the entire IPv6 subsystem. Ubuntu assumes the
# subsystem exists and so does the ansible-os-ubuntu hardening roles.
- name: Disable IPv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

# https://github.com/GSA/datagov-deploy/issues/2655
# Update the last GRUB_CMDLINE_LINUX line and leave ipv6 enabled.
- name: Ensure apparmor and auditing are enabled
  lineinfile: >
    regexp='^GRUB_CMDLINE_LINUX='
    dest=/etc/default/grub
    line='GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor audit=1"'
    state=present
