---
- name: Configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - molecule-notest

- name: Configure /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
  tags:
    - molecule-notest

- name: Specify new hostname through cli
  command: hostname "{{ inventory_hostname }}"
  when: ansible_hostname != inventory_hostname
  tags:
    - molecule-notest
