---
- name: Configure /etc/hosts
  lineinfile:
    line: "127.0.0.1   localhost {{ inventory_hostname }}"
    regexp: "^127.0.0.1"
    dest: /etc/hosts
    state: present
  tags:
    # https://github.com/moby/moby/issues/22281
    - notest

- name: Configure /etc/hostname
  copy:
    content: |
      {{ inventory_hostname }}
    dest: /etc/hostname
    mode: "0644"
    owner: root
    group: root

- name: Specify new hostname through cli
  command: hostname "{{ inventory_hostname }}"
  when: ansible_hostname != inventory_hostname
