---
- include_tasks: hostname.yml

- name: Hardening for Ubuntu Trusty
  include_role:
    name: gsa.ansible-os-ubuntu-14
  when: ansible_distribution_release == "trusty"
  tags:
    - molecule-notest

- name: Hardening for Ubuntu Xenial or Bionic
  include_role:
    name: gsa.ansible-os-ubuntu-16
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"
  tags:
    - molecule-notest

- name: remove incorrectly installed reboot-notify script
  file: dest=/usr/local/reboot-notify.sh state=absent

- name: install reboot-notify script
  template: src=reboot-notify.sh.j2 dest=/usr/local/bin/reboot-notify.sh mode=0755 owner=root group=root
  when:
    - ansible_distribution_release == "trusty"
    - common_reboot_notify_email is defined

# In xenial+ a new package reboot-notifier does this
- name: notify when reboot is required
  cron: >-
    name="notifies when a reboot is required"
    cron_file=reboot-notify
    special_time=daily
    state=present
    job=/usr/local/bin/reboot-notify.sh
    user=root
  when:
    - ansible_distribution_release == "trusty"
    - common_reboot_notify_email is defined

- name: Install upstart for Ubuntu Trusty
  include_role:
    name: dwcramer.upstart
  when: ansible_distribution_release == "trusty"

- name: Install build-essential
  include_role:
    name: ANXS.build-essential

- name: Install apt-utils
  include_role:
    name: ANXS.apt

- include_tasks: system-packages.yml
- include_tasks: tls.yml

- name: Install unattended-upgrades
  include_role:
    name: jnv.unattended-upgrades

- name: Install postfix mail server
  include_role:
    name: oefenweb.postfix

- name: Install newrelic infrastructure agent
  include_role:
    name: newrelic.newrelic-infra
  when: common_newrelic_enabled is true
  tags:
    - molecule-notest      # to fix

- name: Install secops filebeat agent
  include_role:
    name: gsa.ansible-role-beats

- name: Install logrotate
  include_role:
    name: nickhammond.logrotate

- include_tasks: ca-certficates.yml
- include_tasks: grub.yml
- include_tasks: nessus.yml
- include_tasks: ntp.yml
- include_tasks: python-upgrade.yml
- include_tasks: unattended-upgrades-reboot-emails.yml
- include_tasks: trendmicro.yml
  tags:
    - molecule-notest      # to fix
