---
- include_tasks: hostname.yml
  tags:
    - hostname

- name: Hardening for Ubuntu Trusty
  include_role:
    name: gsa.ansible-os-ubuntu-14
  when: ansible_distribution_release == "trusty"
  tags:
    - hardening
    - molecule-notest

- name: Hardening for Ubuntu Xenial or Bionic
  include_role:
    name: gsa.ansible-os-ubuntu-16
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"
  tags:
    - hardening
    - molecule-notest

- name: Install upstart for Ubuntu Trusty
  include_role:
    name: dwcramer.upstart
  when: ansible_distribution_release == "trusty"

- name: Install build-essential
  include_role:
    name: ANXS.build-essential

- name: Install apt-utils
  include_role:
    name: ANXS.apt

- include_tasks: system-packages.yml
  tags:
    - system-packages

- include_tasks: tls.yml
  tags:
    - tls

- name: Install unattended-upgrades
  include_role:
    name: jnv.unattended-upgrades
  tags:
    - unattended-upgrades

- name: Install postfix mail server
  include_role:
    name: oefenweb.postfix
  tags:
    - postfix

- name: Install secops filebeat agent
  include_role:
    name: gsa.ansible-role-beats
  when: filebeat_enabled
  tags:
    - filebeat

- name: Install logrotate
  include_role:
    name: nickhammond.logrotate
  tags:
    - logrotate

- include_tasks: ca-certficates.yml
  tags:
    - ca-certificates

- include_tasks: grub.yml
  tags:
    - grub

- include_tasks: nessus.yml
  when: nessus_agent_enabled
  tags:
    - nessus

- include_tasks: ntp.yml
  tags:
    - ntp

- include_tasks: python-upgrade.yml
  tags:
    - python-upgrade

- include_tasks: reboot-notify.yml
  tags:
    - reboot-notify

- include_tasks: trendmicro.yml
  when: trendmicro_enabled
  tags:
    - trendmicro
    - molecule-notest      # to fix

# Any service monitored by New Relic should've been started by now. We put this
# at the end to avoid getting alerts when first provisioning a machine.
# Otherwise, we'll start monitoring and alerting on things that might not have
# been provisioned yet.
- name: Install newrelic infrastructure agent
  include_role:
    name: newrelic.newrelic-infra
  when: common_newrelic_enabled
  tags:
    - newrelic
    - molecule-notest      # to fix
