---
- name: Hardening for Ubuntu Trusty
  include_role:
    name: gsa.ansible-os-ubuntu-14
  when: ansible_distribution_release == "trusty"

- name: Hardening for Ubuntu Bionic 
  include_role:
    name: gsa.ansible-os-ubuntu-16  
  when: ansible_distribution_release == "bionic"

- name: Install unattended-upgrades
  include_role:
    name: unattended-upgrades

- name: Install postfix 
  include_role:
    name: postfix  

- import_playbook: ntp.yml
- import_playbook: hostname.yml
- import_playbook: ca-certificates.yml
- import_playbook: grub.yml
- import_playbook: hardening.yml
- import_playbook: trendmicro.yml
- import_playbook: filebeats.yml
- import_playbook: misc.yml
- import_playbook: python-upgrade.yml

