---
- import_tasks: hostname.yml
  tags:
    - hostname

- import_tasks: ua.yml
  tags:
    - ua
  when:
    - common_ubuntu_advantage_enabled

- name: Hardening for Ubuntu Trusty
  import_role:
    name: gsa.ansible-os-ubuntu-14
  when: ansible_distribution_release == "trusty"
  tags:
    - hardening
    - molecule-notest

- name: Hardening for Ubuntu Xenial or Bionic
  import_role:
    name: gsa.ansible-os-ubuntu-16
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"
  tags:
    - hardening
    - molecule-notest

- name: Install upstart for Ubuntu Trusty
  import_role:
    name: dwcramer.upstart
  when: ansible_distribution_release == "trusty"
  tags:
    - upstart

- name: Remove broken upstart log rotation
  file: path=/etc/logrotate.d/upstart state=absent
  when: ansible_distribution_release == "trusty"
  tags:
    - upstart

- name: Create block of current user keys
  set_fact:
    common_operator_key_block: "from=\"{{ jumpbox_ip }}\" {{ common_operators | join('\n from=\"{{ jumpbox_ip }}\"', attribute='public_key') }}"

- name: Remove all current user keys
  blockinfile:
    path: /home/ubuntu/.ssh/authorized_keys
    state: absent
    marker: "# {mark} ANSIBLE MANAGED LIST OF USERS"

- name: blockinfile insert
  blockinfile:
    path: /home/ubuntu/.ssh/authorized_keys
    block: "{{ common_operator_key_block }}"
    marker: "# {mark} ANSIBLE MANAGED LIST OF USERS"

- name: Install build-essential
  import_role:
    name: ANXS.build-essential

- name: Install apt-utils
  import_role:
    name: ANXS.apt

- import_tasks: system-packages.yml
  tags:
    - system-packages

- import_tasks: tls.yml
  tags:
    - tls

- name: Install unattended-upgrades
  import_role:
    name: jnv.unattended-upgrades
  tags:
    - unattended-upgrades

- name: Install postfix mail server
  import_role:
    name: oefenweb.postfix
  tags:
    - postfix

- name: Install secops filebeat agent
  import_role:
    name: jobscore.beats
  vars:
    # Don't pin the version, allow filebeat to be updated
    # from apt
    beats_hold_products: false
    beats_ver: "6.*"  # apt-get version specifier. We want the latest 6.x
    beats_products:
      - filebeat
  when: filebeat_enabled
  tags:
    - filebeat

- name: Install logrotate
  import_role:
    name: nickhammond.logrotate
  tags:
    - logrotate

- import_tasks: audit-report.yml
  tags:
    - audit-report

- import_tasks: ca-certficates.yml
  tags:
    - ca-certificates

- import_tasks: grub.yml
  tags:
    - grub

- import_tasks: nessus.yml
  when: nessus_agent_enabled
  tags:
    - nessus

- import_tasks: ntp.yml
  tags:
    - ntp

- import_tasks: python-upgrade.yml
  tags:
    - python-upgrade

- import_tasks: reboot-notify.yml
  tags:
    - reboot-notify

- import_tasks: trendmicro.yml
  when: trendmicro_enabled
  tags:
    - trendmicro
    - molecule-notest      # to fix

# Any service monitored by New Relic should've been started by now. We put this
# at the end to avoid getting alerts when first provisioning a machine.
# Otherwise, we'll start monitoring and alerting on things that might not have
# been provisioned yet.
- name: Install newrelic infrastructure agent
  import_role:
    name: newrelic.newrelic-infra
  when: common_newrelic_enabled
  tags:
    - newrelic
    - molecule-notest      # to fix
