---
- name: Check if python dir exists
  stat: path=/{{ python_version_directory }}/bin/python
  register: python_dir

- name: Check if python was built with shared library
  stat: path=/{{ python_version_directory }}/lib/libpython{{ python_version_number[0:3] }}.so
  register: python_shared_lib

- name: check to python version
  command: /{{ python_version_directory }}/bin/python --version
  register: python_version_check
  failed_when: ("Python " + python_version_number) not in python_version_check.stderr
  # Never report as changed for idempotence
  changed_when: false
  ignore_errors: true
  when: python_dir.stat.exists == True
  tags: skip_ansible_lint

- name: unpack new python
  unarchive:
    src: "{{ python_version_url }}"
    dest: /var/tmp/
    remote_src: yes
  when: python_dir.stat.exists == False or python_version_check is failed or not python_shared_lib.stat.exists

- name: config new python
  command: ./configure --prefix {{ python_version_directory }} --enable-ipv6 --enable-unicode=ucs4 --enable-shared
  args:
    chdir: /var/tmp/{{ python_version_name }}
  when: python_dir.stat.exists == False or python_version_check is failed or not python_shared_lib.stat.exists

- name: install new python
  shell: "umask 022; make && make install"
  args:
    chdir: /var/tmp/{{ python_version_name }}
  when: python_dir.stat.exists == False or python_version_check is failed or not python_shared_lib.stat.exists

# TODO install python to a known prefix like /usr/local to avoid this
- name: add python lib to ld.so.conf
  template: src=etc/ld.so.conf.d/20python.conf dest=/etc/ld.so.conf.d/20python.conf
  register: ubuntu_python_ld_so

- name: update ld.so.cache
  command: ldconfig
  when: ubuntu_python_ld_so is changed
