---
- name: assert trendmicro_policy_id is set
  fail:
    msg: |
      trendmicro_enabled is true but trendmicro_policy_id is not set. All hosts
      in a trendmicro environment should be properly configured with a policy
      id.
  when: trendmicro_policy_id is undefined

- name: Get trendmicro latest .deb package from internal network
  get_url:
    url: "{{ trendmicro_deb_url }}"
    dest: /tmp/trendmicro.deb
    validate_certs: no
    force: yes
  register: result
  retries: 3
  delay: 30
  until: result is success

- name: Install trendmicro
  apt:
    deb: "/tmp/trendmicro.deb"
  register: trendmicro_installed

- name: register trendmicro agent
  command: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id }}"
  when: trendmicro_policy_id is defined
  register: trendmicro_register
  ignore_errors: true
  async: 120
  poll: 10
  retries: 1
  delay: 10
  until: trendmicro_register is success

- name: manually register trendmicro agent
  when: trendmicro_register is failed
  fail:
    msg: >-
      Occasionally trendmicro registration will timeout. Re-run the playbook
      with `--skip-tags trendmicro` and contact the firewall team for them to
      manually register the failed instance or provide debugging support.
