---
- name: assert trendmicro_policy_id is set
  fail:
    msg: |
      trendmicro_enabled is true but trendmicro_policy_id is not set. All hosts
      in a trendmicro environment should be properly configured with a policy
      id.
  when: trendmicro_policy_id is undefined

- name: Get trendmicro latest .deb package from internal network
  get_url:
    url: "{{ trendmicro_deb_url }}"
    dest: /tmp/trendmicro.deb
    validate_certs: no
  register: result
  retries: 3
  delay: 30
  until: result is success

- name: Install trendmicro
  apt:
    deb: "/tmp/trendmicro.deb"
  register: trendmicro_installed

- name: sleep 10 seconds
  command: sleep 10
  when: trendmicro_installed is changed
  tags:
    - skip_ansible_lint

- name: register trendmicro agent
  command: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id }}"
  when: trendmicro_policy_id is defined
