- name: install reboot-notify script
  copy: src=reboot-notify.sh dest=/usr/local/reboot-notify.sh mode=0755 owner=root group=root
  when: ansible_distribution_release == "trusty"

  # In xenial+ a new package reboot-notifier does this
- name: notify when reboot is required
  cron: >-
    name="notifies when a reboot is required"
    cron_file=reboot-notify
    special_time=daily
    state=present
    job=/usr/local/reboot-notify.sh
    user=root
  when: ansible_distribution_release == "trusty"