---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
platforms:
  - name: trusty
    image: ubuntu:trusty
  - name: xenial
    image: ubuntu:xenial
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
  - name: bionic
    image: ubuntu:bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
  inventory:
    group_vars:
      all:
        inactive_operator_key: ssh-rsa key operator_inactive@example.com
scenario:
  name: default
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # to fix
    # - side_effect  # optional
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    n: 2
    v: true
  lint:
    name: flake8
