---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
platforms:
  - name: trusty
    image: ubuntu:trusty
  - name: xenial
    image: ubuntu:xenial
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/sbin/init"
  - name: bionic
    image: ubuntu:bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: testinfra
  lint:
    name: flake8
